# Generated by Django 5.0.4 on 2024-04-18 22:59

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=128, unique=True)),
                ("address_line1", models.CharField(max_length=100)),
                ("address_line2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(blank=True, max_length=50)),
                ("year", models.IntegerField()),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("color", models.CharField(max_length=50)),
                ("engine_capacity", models.IntegerField()),
                ("service_vin", models.CharField(max_length=17, unique=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.vehicletype",
                    ),
                ),
            ],
        ),
    ]
