# Generated by Django 5.0.3 on 2024-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_servicevin_vehicle_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="client",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
