# Generated by Django 5.0.4 on 2024-04-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_vehicle_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="first_app.client",
            ),
        ),
    ]
