# Generated by Django 5.0.4 on 2024-05-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="service_vin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="first_app.servicevin",
            ),
        ),
    ]
