# Generated by Django 5.0.4 on 2024-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0007_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="services",
            field=models.ManyToManyField(blank=True, to="first_app.service"),
        ),
    ]
